[package]
name = "workflow-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
workflow-ir = { path = "../workflow-ir" }
workflow-spec = { path = "../workflow-spec" }

[dev-dependencies]
serde_json.workspace = true
