#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
source_runner="$repo_root/scripts/local-gates.sh"
if [[ ! -x "$source_runner" ]]; then
    printf 'FAIL local-gates helper is missing or not executable: %s\n' "$source_runner" >&2
    exit 1
fi

test_root="$(mktemp -d "${TMPDIR:-/tmp}/adk-local-gates.XXXXXX")"
trap 'rm -rf -- "$test_root"' EXIT
fixture="$test_root/repo"
mkdir -p "$fixture/scripts" "$fixture/bin"
git -C "$fixture" init -q -b main
cp "$source_runner" "$fixture/scripts/local-gates.sh"
printf '%s\n' \
    '.local-gates/' \
    '.csa/' \
    > "$fixture/.gitignore"
printf '%s\n' seed > "$fixture/tracked.txt"
printf '%s\n' \
    '#!/usr/bin/env bash' \
    'set -euo pipefail' \
    '[[ "$*" == "_quality-gates" ]] || { printf "unexpected just args: %s\\n" "$*" >&2; exit 64; }' \
    'printf "run\\n" >> "${FAKE_GATE_LOG:?}"' \
    '[[ "${FAKE_GATE_DIRTY:-0}" != 1 ]] || printf "dirty\\n" >> tracked.txt' \
    '[[ "${FAKE_GATE_FAIL:-0}" != 1 ]] || exit 42' \
    > "$fixture/bin/just"
printf '%s\n' \
    '#!/usr/bin/env bash' \
    'set -euo pipefail' \
    'printf "%s\\n" "$*" > "${FAKE_CSA_LOG:?}"' \
    '[[ "$*" == "review --check-verdict --range main...HEAD" ]]' \
    '[[ "${FAKE_CSA_FAIL:-0}" != 1 ]]' \
    > "$fixture/bin/csa"
chmod +x "$fixture/scripts/local-gates.sh" "$fixture/bin/just" "$fixture/bin/csa"
git -C "$fixture" add .
git -C "$fixture" -c user.name='Gate Test' -c user.email='gate-test@example.invalid' \
    commit -qm 'test: initialize fixture'
mkdir -p "$fixture/.local-gates"
runner="$fixture/scripts/local-gates.sh"
gate_log="$fixture/.local-gates/gate.log"
csa_log="$fixture/.local-gates/csa.log"
assertions=0

lock_fixture="$test_root/lock-mismatch"
cargo_bin="$test_root/cargo-bin"
cargo_log="$test_root/cargo.log"
mkdir -p "$lock_fixture/src" "$cargo_bin"
printf '%s\n' \
    '#!/usr/bin/env bash' \
    'set -euo pipefail' \
    'if [[ "$#" -ne 4 || "$1" != metadata || "$2" != --format-version || "$3" != 1 || "$4" != --locked ]]; then' \
    '    printf "FAIL lock-check invoked cargo with: %s\\n" "$*" >&2' \
    '    exit 64' \
    'fi' \
    'printf "%s\\n" "$@" > "${FAKE_CARGO_LOG:?}"' \
    > "$cargo_bin/cargo"
chmod +x "$cargo_bin/cargo"
printf '%s\n' \
    '[package]' \
    'name = "lock-check-fixture"' \
    'version = "0.2.0"' \
    'edition = "2021"' \
    > "$lock_fixture/Cargo.toml"
printf '%s\n' 'pub fn fixture() {}' > "$lock_fixture/src/lib.rs"
printf '%s\n' \
    '# This file is automatically @generated by Cargo.' \
    '# It is not intended for manual editing.' \
    'version = 4' \
    '' \
    '[[package]]' \
    'name = "lock-check-fixture"' \
    'version = "0.1.0"' \
    > "$lock_fixture/Cargo.lock"
PATH="$cargo_bin:$PATH" FAKE_CARGO_LOG="$cargo_log" \
    just --justfile "$repo_root/justfile" --working-directory "$lock_fixture" lock-check
[[ "$(<"$cargo_log")" == $'metadata\n--format-version\n1\n--locked' ]]
((assertions += 1))
set +e
lock_output="$(just --justfile "$repo_root/justfile" \
    --working-directory "$lock_fixture" lock-check 2>&1)"
lock_rc=$?
set -e
if [[ $lock_rc -eq 0 || "$lock_output" != *'lock file'* ]]; then
    printf 'FAIL lock-check accepted a manifest/lock mismatch: exit=%s output=%s\n' \
        "$lock_rc" "$lock_output" >&2
    exit 1
fi
((assertions += 1))

lefthook_config="$(cd "$repo_root" && lefthook dump)"
if [[ "$lefthook_config" != *$'pre-commit:\n  piped: true\n  commands:\n    branch-protection:\n      run: just check-branch\n    local-gates:\n      run: just pre-commit-fast'* ]]; then
    printf 'FAIL pre-commit hook does not reject main before running local gates\n' >&2
    exit 1
fi
if [[ "$lefthook_config" != *$'pre-push:\n  commands:\n    local-gates:\n      run: just pre-push\n      use_stdin: true'* ]]; then
    printf 'FAIL pre-push hook does not forward Git update records to just pre-push\n' >&2
    exit 1
fi
((assertions += 2))

hook_fixture="$test_root/hook-repo"
mkdir -p "$hook_fixture"
git -C "$hook_fixture" init -q -b main
git -C "$hook_fixture" config user.name 'Gate Test'
git -C "$hook_fixture" config user.email 'gate-test@example.invalid'
printf '%s\n' seed > "$hook_fixture/tracked.txt"
git -C "$hook_fixture" add tracked.txt
git -C "$hook_fixture" commit -qm 'test: initialize hook fixture'
printf '%s\n' staged >> "$hook_fixture/tracked.txt"
git -C "$hook_fixture" add tracked.txt
cp "$repo_root/lefthook.yml" "$hook_fixture/lefthook.yml"
printf '%s\n' \
    'check-branch:' \
    '    @printf "branch-protection\\n" >> hook.log' \
    '    @false' \
    'pre-commit-fast:' \
    '    @printf "local-gates\\n" >> hook.log' \
    > "$hook_fixture/justfile"
set +e
hook_output="$(cd "$hook_fixture" && lefthook run pre-commit 2>&1)"
hook_rc=$?
set -e
if [[ $hook_rc -eq 0 || ! -e "$hook_fixture/hook.log" ||
    "$(<"$hook_fixture/hook.log")" != *branch-protection* ||
    "$(<"$hook_fixture/hook.log")" == *local-gates* ]]; then
    printf 'FAIL pre-commit branch protection started local gates: exit=%s output=%s\n' \
        "$hook_rc" "$hook_output" >&2
    exit 1
fi
((assertions += 1))

invoke() {
    (cd "$fixture" && env \
        PATH="$fixture/bin:$PATH" \
        FAKE_GATE_LOG="$gate_log" \
        FAKE_CSA_LOG="$csa_log" \
        FAKE_GATE_FAIL="${FAKE_GATE_FAIL:-0}" \
        FAKE_GATE_DIRTY="${FAKE_GATE_DIRTY:-0}" \
        FAKE_CSA_FAIL="${FAKE_CSA_FAIL:-0}" \
        "$@")
}

assert_fails() {
    local name="$1" expected="$2" output rc
    shift 2
    set +e
    output="$(invoke "$@" 2>&1)"
    rc=$?
    set -e
    if [[ $rc -eq 0 || "$output" != *"$expected"* ]]; then
        printf 'FAIL %s: exit=%s output=%s\n' "$name" "$rc" "$output" >&2
        exit 1
    fi
    ((assertions += 1))
}

assert_pre_push_fails() {
    local name="$1" expected="$2" records="$3" output rc
    set +e
    if [[ -n "$records" ]]; then
        output="$(printf '%s\n' "$records" | invoke "$runner" pre-push 2>&1)"
    else
        output="$(invoke "$runner" pre-push </dev/null 2>&1)"
    fi
    rc=$?
    set -e
    if [[ $rc -eq 0 || "$output" != *"$expected"* ]]; then
        printf 'FAIL %s: exit=%s output=%s\n' "$name" "$rc" "$output" >&2
        exit 1
    fi
    ((assertions += 1))
}

write_native_receipt() {
    local head tree report_sha256
    mkdir -p "$fixture/.csa"
    printf '%s\n' 'native review report' > "$fixture/.csa/native-review.report"
    head="$(git -C "$fixture" rev-parse HEAD)"
    tree="$(git -C "$fixture" rev-parse HEAD^{tree})"
    report_sha256="$(sha256sum < "$fixture/.csa/native-review.report")"
    printf '%s\n' \
        'schema=adk-workflow-kit-native-review-v1' \
        'status=PASS' \
        "head=$head" \
        "tree=$tree" \
        'range=main...HEAD' \
        "report_sha256=${report_sha256%% *}" \
        "report_path=$fixture/.csa/native-review.report" \
        > "$fixture/.csa/native-review.receipt"
}

assert_fails protected-branch 'main' "$runner" check-branch
git -C "$fixture" switch -qc feature/test
invoke "$runner" check-branch
((assertions += 1))
assert_fails missing-receipt 'missing' "$runner" verify
invoke "$runner" produce
invoke "$runner" verify
((assertions += 2))

current_oid="$(git -C "$fixture" rev-parse HEAD)"
main_oid="$(git -C "$fixture" rev-parse main)"
zero_oid="${current_oid//?/0}"
current_record="refs/heads/feature/test $current_oid refs/heads/feature/test $zero_oid"
git -C "$fixture" switch -qc feature/other
printf '%s\n' unreviewed >> "$fixture/tracked.txt"
git -C "$fixture" add tracked.txt
git -C "$fixture" -c user.name='Gate Test' -c user.email='gate-test@example.invalid' \
    commit -qm 'test: create unreviewed branch'
other_oid="$(git -C "$fixture" rev-parse HEAD)"
git -C "$fixture" switch -q feature/test
other_record="refs/heads/feature/other $other_oid refs/heads/feature/other $main_oid"

assert_pre_push_fails outgoing-other \
    'outgoing local ref must match checked-out branch' "$other_record"
assert_pre_push_fails empty-update 'missing outgoing ref update' ''
assert_pre_push_fails malformed-update 'malformed outgoing ref update' 'malformed'
assert_pre_push_fails deletion-update 'ref deletions are unsupported' \
    "(delete) $zero_oid refs/heads/feature/test $main_oid"
assert_pre_push_fails protected-remote "'refs/heads/main' is protected" \
    "refs/heads/feature/test $current_oid refs/heads/main $main_oid"
assert_pre_push_fails tag-update \
    'outgoing remote ref must match checked-out branch' \
    "refs/heads/feature/test $current_oid refs/tags/test $zero_oid"
assert_pre_push_fails multiple-updates 'multiple outgoing ref updates are unsupported' \
    "$current_record"$'\n'"$other_record"
assert_pre_push_fails mismatched-oid \
    'outgoing object ID does not match reviewed HEAD' \
    "refs/heads/feature/test $other_oid refs/heads/feature/test $main_oid"
printf '%s\n' "$current_record" | invoke "$runner" pre-push
[[ "$(<"$csa_log")" == 'review --check-verdict --range main...HEAD' ]]
((assertions += 2))
CSA_SKIP_REVIEW_CHECK=1 FAKE_CSA_FAIL=1 assert_pre_push_fails native-receipt-missing \
    'CSA review for main...HEAD or a valid native review receipt' "$current_record"
mkdir -p "$fixture/.csa"
printf '%s\n' malformed > "$fixture/.csa/native-review.receipt"
FAKE_CSA_FAIL=1 assert_pre_push_fails native-receipt-malformed \
    'CSA review for main...HEAD or a valid native review receipt' "$current_record"
printf '%s\n' \
    'schema=adk-workflow-kit-native-review-v1' \
    'status=PASS' \
    "head=$zero_oid" \
    "tree=$(git -C "$fixture" rev-parse HEAD^{tree})" \
    'range=main...HEAD' \
    'report_sha256=0000000000000000000000000000000000000000000000000000000000000000' \
    > "$fixture/.csa/native-review.receipt"
FAKE_CSA_FAIL=1 assert_pre_push_fails native-receipt-stale-head \
    'CSA review for main...HEAD or a valid native review receipt' "$current_record"
write_native_receipt
native_output="$(printf '%s\n' "$current_record" | FAKE_CSA_FAIL=1 invoke "$runner" pre-push 2>&1)"
[[ "$native_output" == *'PASS native review receipt for main...'* ]]
((assertions += 1))
rm -rf -- "$fixture/.csa"

printf '%s\n' malformed > "$fixture/.local-gates/quality-gate.receipt"
assert_fails malformed-receipt 'malformed or stale' "$runner" verify
invoke "$runner" produce
printf '%s\n' dirty >> "$fixture/tracked.txt"
assert_fails dirty-tree 'clean' "$runner" verify
git -C "$fixture" restore tracked.txt
printf '%s\n' next >> "$fixture/tracked.txt"
git -C "$fixture" add tracked.txt
git -C "$fixture" -c user.name='Gate Test' -c user.email='gate-test@example.invalid' \
    commit -qm 'test: advance head'
assert_fails stale-receipt 'malformed or stale' "$runner" verify

set +e
FAKE_GATE_FAIL=1 invoke "$runner" produce >/dev/null 2>&1
failure_rc=$?
set -e
[[ $failure_rc -eq 42 && ! -e "$fixture/.local-gates/quality-gate.receipt" ]]
((assertions += 1))

invoke "$runner" produce
set +e
FAKE_GATE_DIRTY=1 invoke "$runner" produce >/dev/null 2>&1
drift_rc=$?
set -e
[[ $drift_rc -ne 0 && ! -e "$fixture/.local-gates/quality-gate.receipt" ]]
((assertions += 1))

printf 'PASS local-gates contract (%d assertions)\n' "$assertions"
