[package]
name = "workflowctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
workflow-compiler = { path = "../workflow-compiler" }
workflow-ir = { path = "../workflow-ir" }
workflow-runtime = { path = "../workflow-runtime" }
workflow-spec = { path = "../workflow-spec" }
workflow-testkit = { path = "../workflow-testkit" }
